/**
 * ChangeCard — the answer to "how much do I hand back?".
 *
 * Implements the ChangeCard row of the DESIGN.md §4 map: `card bg-neutral
 * text-neutral-content` wrapping `MoneyDisplay size="change"` with a
 * denomination hint beneath it. This is the single sanctioned use of the
 * 184–200px step in the type scale, and per §3 the card sits above the keypad
 * below md so the running answer stays visible while the student is still
 * tapping in what the customer handed over.
 *
 * The dark neutral surface is the reason MoneyDisplay carries no colour class:
 * the figure inherits `neutral-content` here and `base-content` everywhere else,
 * which is what keeps the primitive theme-agnostic.
 *
 * The hint is generated by `denominationHint` in `src/lib/money.ts` — greedy
 * largest-first bills and coins — because it is arithmetic over cents and must
 * be unit-tested, not inlined in a component. Callers may override it with
 * `hint` when a drawer cannot make the greedy breakdown.
 */

import { denominationHint } from "@/lib/money";
import { MoneyDisplay } from "./money-display";

export interface ChangeCardProps {
  /** Change owed, in integer cents. Computed by `changeCents`, never here. */
  changeCents: number;
  /** Sentence-case caption above the figure. */
  label?: string;
  /** Overrides the generated "3 one-dollar bills" line. */
  hint?: string;
}

export function ChangeCard({
  changeCents,
  label = "Give back",
  hint,
}: ChangeCardProps) {
  return (
    // A live region, so the answer is read aloud the moment it appears and
    // again whenever the amount received changes.
    <div role="status" aria-atomic="true" className="card bg-neutral text-neutral-content">
      {/* The size container for the change figure, which scales to its width. */}
      <div className="@container card-body w-full items-center gap-2 px-4 text-center md:px-8">
        <p className="text-[18px] font-bold opacity-80">{label}</p>
        <MoneyDisplay cents={changeCents} size="change" />
        <p className="text-[22px] font-extrabold">
          {hint ?? denominationHint(changeCents)}
        </p>
      </div>
    </div>
  );
}
